# Generated by Django 3.2.7 on 2021-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('A', 'Action')], max_length=1)),
                ('image', models.ImageField(upload_to='movie')),
                ('year', models.DateTimeField()),
            ],
        ),
    ]
