# Generated by Django 3.2.7 on 2021-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
