# Generated by Django 3.2.7 on 2021-10-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='description',
            new_name='plot',
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('Action', 'Action')], max_length=10),
        ),
    ]
