# Generated by Django 3.2.7 on 2021-10-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211005_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
    ]
