# Generated by Django 3.2.7 on 2021-10-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movies_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('A', 'Action')], max_length=1),
        ),
    ]
