# Generated by Django 3.2.7 on 2021-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
