# Generated by Django 3.2.7 on 2021-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='movies',
            name='plot',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
