# Generated by Django 3.2.7 on 2021-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211005_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action')], max_length=10),
        ),
    ]
