# Generated by Django 3.2.7 on 2021-10-11 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0017_alter_play_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='play',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
