# Generated by Django 3.2.7 on 2021-10-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
    ]
