# Generated by Django 3.2.7 on 2021-11-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_review_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
