# Generated by Django 3.2.7 on 2021-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_remove_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='year',
            field=models.DateField(),
        ),
    ]
