# Generated by Django 3.2.7 on 2021-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_alter_play_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
